name: 'Comment Run Actions'
description: 'Execute any script in a GitHub issue comment'
author: 'Ryo Ota <nwtgck@nwtgck.org>'
inputs:
  github-token:
    description: 'GitHub token'
    required: true
  allowed-associations:
    description: Comment author associations allowed to execute scripts (e.g. '["OWNER", "COLLABORATOR"]')
    default: '["OWNER"]'
runs:
  using: 'node20'
  main: 'dist/index.js'
