name: 'Comment Run Actions'
description: 'Execute any script in a GitHub issue comment'
author: 'Ryo Ota <nwtgck@nwtgck.org>'
inputs:
  github-token:
    description: 'GitHub token'
    required: true
  allowed-associations:
    description: Comment author associations allowed to execute scripts (e.g. '["OWNER", "COLLABORATOR"]')
    default: '["OWNER"]'
  allowed-users:
    description: Users who are allowed to execute scripts *regardless* of their comment author association, which is useful in org-owned repos where only the organization itself has the OWNER association
    default: '[]'
runs:
  using: 'node12'
  main: 'dist/index.js'
