name: "operational-test"
on:
  # (from: https://help.github.com/en/actions/reference/events-that-trigger-workflows#issue-comment-event-issue_comment)
  issue_comment:
    types: [created, edited]

jobs:
  test: # make sure the action works on a clean machine without building
    # Skip the job if the comment does not conatin the trigger phrase
    if: contains(github.event.comment.body, '@github-actions run')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # 0 indicates all history
        fetch-depth: 0
    - uses: ./
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
